apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: elkia
build:
  artifacts:
    - image: ghcr.io/infinity-blackhole/elkia-authserver
      context: .
      runtimeType: go
      docker:
        target: build
        dockerfile: cmd/elkia-authserver/Dockerfile
    - image: ghcr.io/infinity-blackhole/elkia-fleet
      context: .
      runtimeType: go
      docker:
        target: build
        dockerfile: cmd/elkia-fleet/Dockerfile
    - image: ghcr.io/infinity-blackhole/elkia-gateway
      context: .
      runtimeType: go
      docker:
        target: build
        dockerfile: cmd/elkia-gateway/Dockerfile
  local:
    useBuildkit: true
manifests:
  kustomize:
    paths:
      - manifests/elkia/overlays/default
---
apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: elkia-base
manifests:
  kustomize:
    paths:
      - manifests/kratos/overlays/default
      - manifests/kratos-selfservice-ui-node/overlays/default
      - manifests/etcd/overlays/default
      - manifests/kafka/overlays/default
    buildArgs:
      - --enable-helm
deploy:
  statusCheckDeadlineSeconds: 600
  tolerateFailuresUntilDeadline: true