apiVersion: skaffold/v4beta2
kind: Config
metadata:
  name: elkia
build:
  artifacts:
    - image: ghcr.io/infinity-blackhole/elkia-auth
      context: .
      runtimeType: go
      docker:
        target: build
        dockerfile: cmd/elkia-auth/Dockerfile
    - image: ghcr.io/infinity-blackhole/elkia-auth-proxy
      context: .
      runtimeType: go
      docker:
        target: build
        dockerfile: cmd/elkia-auth-proxy/Dockerfile
    - image: ghcr.io/infinity-blackhole/elkia-gateway
      context: .
      runtimeType: go
      docker:
        target: build
        dockerfile: cmd/elkia-gateway/Dockerfile
    - image: ghcr.io/infinity-blackhole/elkia-gateway-proxy
      context: .
      runtimeType: go
      docker:
        target: build
        dockerfile: cmd/elkia-gateway-proxy/Dockerfile
    - image: ghcr.io/infinity-blackhole/elkia-fleet
      context: .
      runtimeType: go
      docker:
        target: build
        dockerfile: cmd/elkia-fleet/Dockerfile
    - image: ghcr.io/infinity-blackhole/elkia-world
      context: .
      runtimeType: go
      docker:
        target: build
        dockerfile: cmd/elkia-world/Dockerfile
  local:
    useBuildkit: true
manifests:
  kustomize:
    paths:
      - manifests/elkia/overlays/shikanime
    buildArgs:
      - --enable-helm
deploy:
  statusCheckDeadlineSeconds: 600
  tolerateFailuresUntilDeadline: true
