apiVersion: apps/v1
kind: Deployment
metadata:
  name: elkia-gateway
  namespace: elkia
spec:
  template:
    spec:
      containers:
        - name: elkia-gateway
          env:
            - name: ELKIA_FLEET_ENDPOINT
              value: elkia-fleet:8080
