apiVersion: apps/v1
kind: Deployment
metadata:
  name: elkia-fleet
  namespace: elkia
spec:
  template:
    spec:
      containers:
        - name: elkia-fleet
          env:
            - name: LOG_LEVEL
              value: debug
            - name: KRATOS_URIS
              value: https://hungry-wilson-nrizdiygxs.projects.oryapis.com
            - name: REDIS_ENDPOINTS
              value: redis-12998.c304.europe-west1-2.gce.cloud.redislabs.com:12998
