apiVersion: apps/v1
kind: Deployment
metadata:
  name: elkia-world
  namespace: elkia
  labels:
    app.kubernetes.io/name: elkia-world
    app.kubernetes.io/instance: elkia-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: elkia-world
      app.kubernetes.io/instance: elkia-world
  template:
    metadata:
      labels:
        app.kubernetes.io/name: elkia-world
        app.kubernetes.io/instance: elkia-world
    spec:
      containers:
        - name: elkia-world
          image: elkia-world
          env:
            - name: HOST
              value: "0.0.0.0"
          ports:
            - containerPort: 8080
              name: http
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 512Mi
