apiVersion: v1
kind: Service
metadata:
  name: elkia-world
  namespace: elkia
  labels:
    app.kubernetes.io/name: elkia-world
    app.kubernetes.io/instance: elkia-world
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app.kubernetes.io/name: elkia-world
    app.kubernetes.io/instance: elkia-world
