apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kratos-courier
  namespace: elkia
spec:
  template:
    spec:
      containers:
        - name: kratos-courier
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: mysql-root-password
            - name: DSN
              value: mysql://root:$(MYSQL_ROOT_PASSWORD)@tcp(mysql:3306)/kratos?max_conns=20&max_idle_conns=4
