CREATE TABLE IF NOT EXISTS characters (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    name TEXT NOT NULL UNIQUE,
    class INTEGER DEFAULT 0,
    level INTEGER DEFAULT 1,
    hero_level INTEGER DEFAULT 0,
    job_level INTEGER DEFAULT 0,
    experience INTEGER DEFAULT 0,
    job_experience INTEGER DEFAULT 0,
    hero_experience INTEGER DEFAULT 0,
    faction INTEGER DEFAULT 0,
    reputation INTEGER DEFAULT 0,
    dignity INTEGER DEFAULT 0,
    compliment INTEGER DEFAULT 0,
    health INTEGER DEFAULT 100,
    mana INTEGER DEFAULT 100,
    hair_color INTEGER DEFAULT 0,
    hair_style INTEGER DEFAULT 0,
    x INTEGER DEFAULT 0,
    y INTEGER DEFAULT 0,
    map_id INTEGER DEFAULT 0,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(user_id) REFERENCES users(id)
);
