apiVersion: apps/v1
kind: Deployment
metadata:
  name: kratos-selfservice-ui-node
  namespace: elkia
spec:
  template:
    spec:
      containers:
        - name: kratos-selfservice-ui-node
          env:
            - name: KRATOS_BROWSER_URL
              value: http://accounts.elkia.localhost/.ory/kratos/public
            - name: JWKS_URL
              value: http://elkia.localhost/.well-known/jwks.json
