apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: elkia
helmCharts:
  - name: kratos-selfservice-ui-node
    namespace: elkia
    repo: https://k8s.ory.sh/helm/charts
    version: "0.28.0"
    releaseName: kratos-selfservice-ui-node
    valuesInline:
      kratosBrowserUrl: http://kratos.elkia.localhost/
      kratosPublicUrl: http://kratos-public/
      kratosAdminUrl: http://kratos-admin/
