apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  - ../../components/elkia-apiserver
  - ../../components/kafka
patches:
  - path: deployment.patch.yaml
