apiVersion: apps/v1
kind: Deployment
metadata:
  name: elkia-auth
  namespace: elkia
  labels:
    app.kubernetes.io/name: elkia-auth
    app.kubernetes.io/instance: elkia-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: elkia-auth
      app.kubernetes.io/instance: elkia-auth
  template:
    metadata:
      labels:
        app.kubernetes.io/name: elkia-auth
        app.kubernetes.io/instance: elkia-auth
    spec:
      containers:
        - name: elkia-auth
          image: ghcr.io/infinity-blackhole/elkia-auth
          env:
            - name: HOST
              value: "0.0.0.0"
          ports:
            - containerPort: 8080
              name: http
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 100m
              memory: 512Mi
