apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  - ../../components/etcd
  - ../../components/kratos
patches:
  - path: deployment.patch.yaml
  - path: svc.patch.yaml
