apiVersion: apps/v1
kind: Deployment
metadata:
  name: elkia-world
  namespace: elkia
spec:
  template:
    spec:
      containers:
        - name: elkia-world
          env:
            - name: KRATOS_URIS
              value: http://kratos-public
