version: v0.11.1
ciphers:
  algorithm: xchacha20-poly1305
hashers:
  algorithm: bcrypt
  bcrypt:
    cost: 8
identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///etc/kratos/identity.default.schema.json
log:
  format: text
  leak_sensitive_values: true
  level: debug
selfservice:
  allowed_return_urls:
    - http://accounts.elkia.localhost
  default_browser_return_url: http://accounts.elkia.localhost/
  flows:
    error:
      ui_url: http://accounts.elkia.localhost/error
    login:
      lifespan: 10m
      ui_url: http://accounts.elkia.localhost/login
    logout:
      after:
        default_browser_return_url: http://accounts.elkia.localhost/login
    recovery:
      enabled: true
      ui_url: http://accounts.elkia.localhost/recovery
      use: code
    registration:
      after:
        password:
          hooks:
            - hook: session
      lifespan: 10m
      ui_url: http://accounts.elkia.localhost/registration
    settings:
      privileged_session_max_age: 15m
      required_aal: highest_available
      ui_url: http://accounts.elkia.localhost/settings
    verification:
      after:
        default_browser_return_url: http://accounts.elkia.localhost/
      enabled: true
      ui_url: http://accounts.elkia.localhost/verification
      use: code
  methods:
    code:
      enabled: true
    link:
      enabled: true
    lookup_secret:
      enabled: true
    password:
      enabled: true
    totp:
      config:
        issuer: Kratos
      enabled: true
serve:
  admin:
    base_url: http://kratos-admin
    port: 4434
  public:
    base_url: http://accounts.elkia.localhost/.ory/kratos/public/
    cors:
      enabled: true
    port: 4433
session:
  cookie:
    domain: elkia.localhost
