apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: mysql
    namespace: elkia
    repo: https://charts.bitnami.com/bitnami
    version: "9.4.8"
    releaseName: mysql
    valuesInline:
      auth:
        rootPassword: n4BXtC32XLx5C8
        database: kratos
