// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: pkg/api/distribution/v1alpha1/distribution.proto

package v1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ArtifactVerifyResult int32

const (
	ArtifactVerifyResult_UNKNOWN  ArtifactVerifyResult = 0
	ArtifactVerifyResult_SUCCESS  ArtifactVerifyResult = 1
	ArtifactVerifyResult_FAILURE  ArtifactVerifyResult = 2
	ArtifactVerifyResult_OUTDATED ArtifactVerifyResult = 3
)

// Enum value maps for ArtifactVerifyResult.
var (
	ArtifactVerifyResult_name = map[int32]string{
		0: "UNKNOWN",
		1: "SUCCESS",
		2: "FAILURE",
		3: "OUTDATED",
	}
	ArtifactVerifyResult_value = map[string]int32{
		"UNKNOWN":  0,
		"SUCCESS":  1,
		"FAILURE":  2,
		"OUTDATED": 3,
	}
)

func (x ArtifactVerifyResult) Enum() *ArtifactVerifyResult {
	p := new(ArtifactVerifyResult)
	*p = x
	return p
}

func (x ArtifactVerifyResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ArtifactVerifyResult) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_api_distribution_v1alpha1_distribution_proto_enumTypes[0].Descriptor()
}

func (ArtifactVerifyResult) Type() protoreflect.EnumType {
	return &file_pkg_api_distribution_v1alpha1_distribution_proto_enumTypes[0]
}

func (x ArtifactVerifyResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ArtifactVerifyResult.Descriptor instead.
func (ArtifactVerifyResult) EnumDescriptor() ([]byte, []int) {
	return file_pkg_api_distribution_v1alpha1_distribution_proto_rawDescGZIP(), []int{0}
}

type ArtifactVerifyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version  string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Checksum string `protobuf:"bytes,2,opt,name=checksum,proto3" json:"checksum,omitempty"`
}

func (x *ArtifactVerifyRequest) Reset() {
	*x = ArtifactVerifyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_distribution_v1alpha1_distribution_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArtifactVerifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactVerifyRequest) ProtoMessage() {}

func (x *ArtifactVerifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_distribution_v1alpha1_distribution_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactVerifyRequest.ProtoReflect.Descriptor instead.
func (*ArtifactVerifyRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_distribution_v1alpha1_distribution_proto_rawDescGZIP(), []int{0}
}

func (x *ArtifactVerifyRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ArtifactVerifyRequest) GetChecksum() string {
	if x != nil {
		return x.Checksum
	}
	return ""
}

type ArtifactVerifyResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result ArtifactVerifyResult `protobuf:"varint,1,opt,name=result,proto3,enum=io.elkia.distribution.v1alpha1.ArtifactVerifyResult" json:"result,omitempty"`
}

func (x *ArtifactVerifyResponse) Reset() {
	*x = ArtifactVerifyResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_distribution_v1alpha1_distribution_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArtifactVerifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactVerifyResponse) ProtoMessage() {}

func (x *ArtifactVerifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_distribution_v1alpha1_distribution_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactVerifyResponse.ProtoReflect.Descriptor instead.
func (*ArtifactVerifyResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_distribution_v1alpha1_distribution_proto_rawDescGZIP(), []int{1}
}

func (x *ArtifactVerifyResponse) GetResult() ArtifactVerifyResult {
	if x != nil {
		return x.Result
	}
	return ArtifactVerifyResult_UNKNOWN
}

var File_pkg_api_distribution_v1alpha1_distribution_proto protoreflect.FileDescriptor

var file_pkg_api_distribution_v1alpha1_distribution_proto_rawDesc = []byte{
	0x0a, 0x30, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69,
	0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2f,
	0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x1e, 0x69, 0x6f, 0x2e, 0x65, 0x6c, 0x6b, 0x69, 0x61, 0x2e, 0x64, 0x69, 0x73,
	0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68,
	0x61, 0x31, 0x22, 0x4d, 0x0a, 0x15, 0x41, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x56, 0x65,
	0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x75,
	0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x73, 0x75,
	0x6d, 0x22, 0x66, 0x0a, 0x16, 0x41, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x56, 0x65, 0x72,
	0x69, 0x66, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4c, 0x0a, 0x06, 0x72,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x34, 0x2e, 0x69, 0x6f,
	0x2e, 0x65, 0x6c, 0x6b, 0x69, 0x61, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x41, 0x72, 0x74,
	0x69, 0x66, 0x61, 0x63, 0x74, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x2a, 0x4b, 0x0a, 0x14, 0x41, 0x72, 0x74,
	0x69, 0x66, 0x61, 0x63, 0x74, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x0b,
	0x0a, 0x07, 0x53, 0x55, 0x43, 0x43, 0x45, 0x53, 0x53, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x46,
	0x41, 0x49, 0x4c, 0x55, 0x52, 0x45, 0x10, 0x02, 0x12, 0x0c, 0x0a, 0x08, 0x4f, 0x55, 0x54, 0x44,
	0x41, 0x54, 0x45, 0x44, 0x10, 0x03, 0x32, 0x8c, 0x01, 0x0a, 0x06, 0x43, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x12, 0x81, 0x01, 0x0a, 0x0e, 0x41, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x56, 0x65,
	0x72, 0x69, 0x66, 0x79, 0x12, 0x35, 0x2e, 0x69, 0x6f, 0x2e, 0x65, 0x6c, 0x6b, 0x69, 0x61, 0x2e,
	0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x61,
	0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x41, 0x72, 0x74, 0x69, 0x66, 0x61, 0x63, 0x74, 0x56, 0x65,
	0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x36, 0x2e, 0x69, 0x6f,
	0x2e, 0x65, 0x6c, 0x6b, 0x69, 0x61, 0x2e, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x76, 0x31, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x2e, 0x41, 0x72, 0x74,
	0x69, 0x66, 0x61, 0x63, 0x74, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x1f, 0x5a, 0x1d, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x64, 0x69, 0x73, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x76, 0x31,
	0x61, 0x6c, 0x70, 0x68, 0x61, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_api_distribution_v1alpha1_distribution_proto_rawDescOnce sync.Once
	file_pkg_api_distribution_v1alpha1_distribution_proto_rawDescData = file_pkg_api_distribution_v1alpha1_distribution_proto_rawDesc
)

func file_pkg_api_distribution_v1alpha1_distribution_proto_rawDescGZIP() []byte {
	file_pkg_api_distribution_v1alpha1_distribution_proto_rawDescOnce.Do(func() {
		file_pkg_api_distribution_v1alpha1_distribution_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_api_distribution_v1alpha1_distribution_proto_rawDescData)
	})
	return file_pkg_api_distribution_v1alpha1_distribution_proto_rawDescData
}

var file_pkg_api_distribution_v1alpha1_distribution_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_api_distribution_v1alpha1_distribution_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_api_distribution_v1alpha1_distribution_proto_goTypes = []interface{}{
	(ArtifactVerifyResult)(0),      // 0: io.elkia.distribution.v1alpha1.ArtifactVerifyResult
	(*ArtifactVerifyRequest)(nil),  // 1: io.elkia.distribution.v1alpha1.ArtifactVerifyRequest
	(*ArtifactVerifyResponse)(nil), // 2: io.elkia.distribution.v1alpha1.ArtifactVerifyResponse
}
var file_pkg_api_distribution_v1alpha1_distribution_proto_depIdxs = []int32{
	0, // 0: io.elkia.distribution.v1alpha1.ArtifactVerifyResponse.result:type_name -> io.elkia.distribution.v1alpha1.ArtifactVerifyResult
	1, // 1: io.elkia.distribution.v1alpha1.Client.ArtifactVerify:input_type -> io.elkia.distribution.v1alpha1.ArtifactVerifyRequest
	2, // 2: io.elkia.distribution.v1alpha1.Client.ArtifactVerify:output_type -> io.elkia.distribution.v1alpha1.ArtifactVerifyResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_api_distribution_v1alpha1_distribution_proto_init() }
func file_pkg_api_distribution_v1alpha1_distribution_proto_init() {
	if File_pkg_api_distribution_v1alpha1_distribution_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_api_distribution_v1alpha1_distribution_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArtifactVerifyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_distribution_v1alpha1_distribution_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArtifactVerifyResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_api_distribution_v1alpha1_distribution_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_api_distribution_v1alpha1_distribution_proto_goTypes,
		DependencyIndexes: file_pkg_api_distribution_v1alpha1_distribution_proto_depIdxs,
		EnumInfos:         file_pkg_api_distribution_v1alpha1_distribution_proto_enumTypes,
		MessageInfos:      file_pkg_api_distribution_v1alpha1_distribution_proto_msgTypes,
	}.Build()
	File_pkg_api_distribution_v1alpha1_distribution_proto = out.File
	file_pkg_api_distribution_v1alpha1_distribution_proto_rawDesc = nil
	file_pkg_api_distribution_v1alpha1_distribution_proto_goTypes = nil
	file_pkg_api_distribution_v1alpha1_distribution_proto_depIdxs = nil
}
