apiVersion: apps/v1
kind: Deployment
metadata:
  name: elkia-world
  namespace: elkia
spec:
  template:
    spec:
      containers:
        - name: elkia-world
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql
                  key: mysql-root-password
            - name: DSN
              value: "mysql://root:$(MYSQL_ROOT_PASSWORD)@tcp(mysql:3306)/elkia?charset=utf8mb4&parseTime=True&loc=Local"
