apiVersion: apps/v1
kind: Deployment
metadata:
  name: elkia-gateway
  namespace: elkia
spec:
  template:
    spec:
      containers:
        - name: elkia-gateway
          env:
            - name: LOG_LEVEL
              value: debug
            - name: REDIS_ENDPOINTS
              value: redis-12998.c304.europe-west1-2.gce.cloud.redislabs.com:12998
