apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
components:
  - ../../components/elkia-fleet
  - ../../components/redis
patches:
  - path: deployment.patch.yaml
