apiVersion: v1
kind: Service
metadata:
  name: kratos-selfservice-ui-node
  labels:
    app.kubernetes.io/name: kratos-selfservice-ui-node
    app.kubernetes.io/instance: kratos-selfservice-ui-node
spec:
  ports:
    - port: 80
      targetPort: http
      name: http
  selector:
    app.kubernetes.io/name: kratos-selfservice-ui-node
    app.kubernetes.io/instance: kratos-selfservice-ui-node
