apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: kafka
    namespace: elkia
    repo: https://charts.bitnami.com/bitnami
    version: "20.0.6"
    releaseName: kafka
