apiVersion: v1
kind: Service
metadata:
  name: elkia-authserver
  namespace: elkia
spec:
  ports:
    - name: elkia
      port: 4123
      targetPort: elkia
  selector:
    app.kubernetes.io/name: elkia-authserver
    app.kubernetes.io/instance: elkia-authserver
