[package]
name = "elkia-gateway"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.36", features = ["full"] }
clap = { version = "4.5", features = ["derive", "env"] }
log = "0.4"
env_logger = "0.11"
bytes = "1.5"
futures = "0.3"
tokio-util = { version = "0.7", features = ["codec"] }
elkia-net = { path = "../elkia-net" }
