apiVersion: apps/v1
kind: Deployment
metadata:
  name: elkia-apiserver
  namespace: elkia
  labels:
    app.kubernetes.io/name: elkia-apiserver
    app.kubernetes.io/instance: elkia-apiserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: elkia-apiserver
      app.kubernetes.io/instance: elkia-apiserver
  template:
    metadata:
      labels:
        app.kubernetes.io/name: elkia-apiserver
        app.kubernetes.io/instance: elkia-apiserver
    spec:
      containers:
        - name: elkia-apiserver
          image: ghcr.io/infinity-blackhole/elkia-apiserver
          env:
            - name: HOST
              value: "0.0.0.0"
          ports:
            - containerPort: 8080
              name: http
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 128Mi
      serviceAccountName: elkia-apiserver
