// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: pkg/api/eventing/v1alpha1/channel.proto

package v1alpha1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Gateway_ChannelInteract_FullMethodName = "/shikanime.elkia.eventing.v1alpha1.Gateway/ChannelInteract"
)

// GatewayClient is the client API for Gateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GatewayClient interface {
	// ChannelInteract is a bi-directional stream that is used to interact with
	// the channel server
	ChannelInteract(ctx context.Context, opts ...grpc.CallOption) (Gateway_ChannelInteractClient, error)
}

type gatewayClient struct {
	cc grpc.ClientConnInterface
}

func NewGatewayClient(cc grpc.ClientConnInterface) GatewayClient {
	return &gatewayClient{cc}
}

func (c *gatewayClient) ChannelInteract(ctx context.Context, opts ...grpc.CallOption) (Gateway_ChannelInteractClient, error) {
	stream, err := c.cc.NewStream(ctx, &Gateway_ServiceDesc.Streams[0], Gateway_ChannelInteract_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &gatewayChannelInteractClient{stream}
	return x, nil
}

type Gateway_ChannelInteractClient interface {
	Send(*ChannelInteractRequest) error
	Recv() (*ChannelEvent, error)
	grpc.ClientStream
}

type gatewayChannelInteractClient struct {
	grpc.ClientStream
}

func (x *gatewayChannelInteractClient) Send(m *ChannelInteractRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *gatewayChannelInteractClient) Recv() (*ChannelEvent, error) {
	m := new(ChannelEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GatewayServer is the server API for Gateway service.
// All implementations must embed UnimplementedGatewayServer
// for forward compatibility
type GatewayServer interface {
	// ChannelInteract is a bi-directional stream that is used to interact with
	// the channel server
	ChannelInteract(Gateway_ChannelInteractServer) error
	mustEmbedUnimplementedGatewayServer()
}

// UnimplementedGatewayServer must be embedded to have forward compatible implementations.
type UnimplementedGatewayServer struct {
}

func (UnimplementedGatewayServer) ChannelInteract(Gateway_ChannelInteractServer) error {
	return status.Errorf(codes.Unimplemented, "method ChannelInteract not implemented")
}
func (UnimplementedGatewayServer) mustEmbedUnimplementedGatewayServer() {}

// UnsafeGatewayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GatewayServer will
// result in compilation errors.
type UnsafeGatewayServer interface {
	mustEmbedUnimplementedGatewayServer()
}

func RegisterGatewayServer(s grpc.ServiceRegistrar, srv GatewayServer) {
	s.RegisterService(&Gateway_ServiceDesc, srv)
}

func _Gateway_ChannelInteract_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GatewayServer).ChannelInteract(&gatewayChannelInteractServer{stream})
}

type Gateway_ChannelInteractServer interface {
	Send(*ChannelEvent) error
	Recv() (*ChannelInteractRequest, error)
	grpc.ServerStream
}

type gatewayChannelInteractServer struct {
	grpc.ServerStream
}

func (x *gatewayChannelInteractServer) Send(m *ChannelEvent) error {
	return x.ServerStream.SendMsg(m)
}

func (x *gatewayChannelInteractServer) Recv() (*ChannelInteractRequest, error) {
	m := new(ChannelInteractRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Gateway_ServiceDesc is the grpc.ServiceDesc for Gateway service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Gateway_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shikanime.elkia.eventing.v1alpha1.Gateway",
	HandlerType: (*GatewayServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ChannelInteract",
			Handler:       _Gateway_ChannelInteract_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "pkg/api/eventing/v1alpha1/channel.proto",
}
