apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: elkia-fleet-service-agent
  namespace: elkia
rules:
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: elkia-fleet-service-agent
  namespace: elkia
subjects:
  - kind: ServiceAccount
    name: elkia-fleet
    namespace: elkia
    apiGroup: ""
roleRef:
  kind: Role
  name: elkia-fleet-service-agent
  apiGroup: rbac.authorization.k8s.io
