apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: elkia-fleet-service-agent
  namespace: elkia
rules:
- apiGroups: [""]
  resources: ["namespaces", "services"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: elkia-fleet-service-agent
  namespace: elkia
subjects:
- kind: ServiceAccount
  name: elkia-fleet
  namespace: elkia
  apiGroup: ""
roleRef:
  kind: ClusterRole
  name: namespace-reader
  apiGroup: rbac.authorization.k8s.io