apiVersion: apps/v1
kind: Deployment
metadata:
  name: kratos
  namespace: elkia
  labels:
    app.kubernetes.io/name: kratos
    app.kubernetes.io/instance: kratos
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: kratos
      app.kubernetes.io/instance: kratos
  template:
    metadata:
      labels:
        app.kubernetes.io/name: kratos
        app.kubernetes.io/instance: kratos
    spec:
      volumes:
        - name: kratos-config
          configMap:
            name: kratos
      initContainers:
        - name: kratos-automigrate
          image: oryd/kratos:v0.11.1
          command:
            - kratos
          args:
            - migrate
            - sql
            - -e
            - --yes
            - --config
            - /etc/kratos/kratos.yaml
          volumeMounts:
            - name: kratos-config
              mountPath: /etc/kratos
              readOnly: true
          env:
            - name: DSN
              valueFrom:
                secretKeyRef:
                  name: kratos
                  key: dsn
      containers:
        - name: kratos
          image: oryd/kratos:v0.11.1
          command:
            - kratos
          args:
            - serve
            - all
            - --config
            - /etc/kratos/kratos.yaml
          volumeMounts:
            - name: kratos-config
              mountPath: /etc/kratos
              readOnly: true
          env:
            - name: DSN
              valueFrom:
                secretKeyRef:
                  name: kratos
                  key: dsn
            - name: SECRETS_DEFAULT
              valueFrom:
                secretKeyRef:
                  name: kratos
                  key: secretsDefault
                  optional: true
            - name: SECRETS_COOKIE
              valueFrom:
                secretKeyRef:
                  name: kratos
                  key: secretsCookie
                  optional: true
            - name: SECRETS_CIPHER
              valueFrom:
                secretKeyRef:
                  name: kratos
                  key: secretsCipher
                  optional: true
            - name: COURIER_SMTP_CONNECTION_URI
              valueFrom:
                secretKeyRef:
                  name: kratos
                  key: smtpConnectionURI
          ports:
            - name: http-admin
              containerPort: 4434
            - name: http-public
              containerPort: 4433
          livenessProbe:
            httpGet:
              path: /admin/health/ready
              port: 4434
              httpHeaders:
                - name: Host
                  value: "127.0.0.1"
          readinessProbe:
            httpGet:
              path: /admin/health/ready
              port: 4434
              httpHeaders:
                - name: Host
                  value: "127.0.0.1"
          startupProbe:
            httpGet:
              path: /admin/health/ready
              port: 4434
              httpHeaders:
                - name: Host
                  value: "127.0.0.1"
          resources:
            requests:
              cpu: 10m
              memory: 16Mi
            limits:
              cpu: 100m
              memory: 128Mi
