apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - svc.yaml
  - sts.yaml
configMapGenerator:
  - name: kratos
    namespace: elkia
    files:
      - kratos/kratos.yaml
      - kratos/identity.default.schema.json
