apiVersion: apps/v1
kind: Deployment
metadata:
  name: elkia-auth
  namespace: elkia
spec:
  template:
    spec:
      containers:
        - name: elkia-auth
          env:
            - name: LOG_LEVEL
              value: debug
